spring:
  application:
    name: myth-pms
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql:///wlliu_blog?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
  zipkin:
    base-url: http://127.0.0.1:9411/
    discovery-client-enabled: false
  sleuth:
    sampler:
      probability: 1.0
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8719
        dashboard: localhost:8080
mybatis-plus:
  type-aliases-package: com.wlliu.entity
  mapper-locations: classpath:mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 6020
fdfs:
  so-timeout: 6000 #超时时间
  connect-timeout: 6000 #连接超时时间
  #thumb-image: #缩略图
  #  width: 200
  #  height: 200
  tracker-list: #踪迹服务器tracker地址
    - 47.100.202.70:22122
minio:
  endpoint: http://47.100.202.70:9000/
  accessKey: minioaccess
  secretKey: miniosecret